language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
env:
  global:
  - PGPORT=5432
  - NODE_ENV=test
before_script:
  - psql -c 'create database barefoot;' -U postgres
script:
  - npm run test
notifications:
  - email: false
